stages:
  - test

test:
  stage: test
  image: python:${PYTHON_VERSION}
  parallel:
    matrix:
      - PYTHON_VERSION:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
  script:
    - python -m pip install --upgrade pip
    - python -m pip install -e ".[dev]"
    - python -m scripts.ci
